### PR TITLE
fix: display incorrect when children of mask changed.

### LINKED ISSUE #218: 某个场景下使⽤ svg 的⼦组件没有重新渲染
如下，showRect 的值变更不⽣效
```
import * as React from "react";
import { TouchableOpacity, View, Text } from "react-native";
import Svg, { Defs, Mask, Rect, SvgCss, SvgXml } from "react-native-svg";
import { useState } from "react";
export const SvgDemo = React.memo((props: {}) => {
 const [showRect, setShowRect] = useState(false);
 const ScreenHeight = 400;
 const ScreenWidth = 200;
 const RectHeight = 50;
 const RectWidth = 70;
 return (
  <>
   <Svg height="500" width="500">
    <Defs>
     <Mask id="mask" x="0" y="0" height={ScreenHeight} width={ScreenWidth}>
      <Rect height={ScreenHeight} width={ScreenWidth} fill="#fff" />
     {/* 镂空 */}
     {showRect && (
       <Rect
        height={RectHeight}
        rx={10}
        width={RectWidth}
        fill="#000"
        translateX={10}
        translateY={20}
       />
     )}
     </Mask>
    </Defs>
    <Rect
     height={ScreenHeight}
     width={ScreenWidth}
     fill="rgba(0, 0, 0, 0.8)"
     mask="url(#mask)"
     fill-opacity="0"
    />
   </Svg>
   <TouchableOpacity
    onPress={() => {
     setShowRect(!showRect);
   }}
    style={{
     width: 100,
     height: 100,
     backgroundColor: "red"
   }}>
    <Text>{"切换 Rect"}</Text>
   </TouchableOpacity>
  </>
);
});
```

### PR DESCRIPTION
**Pull request by xlleng1**
# Summary
fix: display incorrect when children of mask changed.

# Test Plan
Test is available in svgDemoCases IssueFix section as Issue#218

Resolve [#218 ](https://github.com/react-native-oh-library/react-native-harmony-svg/issues/218)

### CODE REVIEW

File: tester/svgDemoCases/components/IssueFix.tsx [hunk 1]
```diff
@@ -16,10 +16,11 @@ import Svg, {
   Symbol,
   Defs,
   LinearGradient,
+  Mask,
   Stop,
   SvgXml,
 } from 'react-native-svg';
-import { View, StyleSheet, ScrollView, Text, Button } from 'react-native';
+import { View, StyleSheet, ScrollView, Text, Button,TouchableOpacity } from 'react-native';
```
Comment (Louis-C7) [inline tester/svgDemoCases/components/IssueFix.tsx]: 少了空格

**Review by Louis-C7 — CHANGES_REQUESTED** [review]

File: tester/svgDemoCases/components/IssueFix.tsx (hunk 1 above)
Comment (xlleng1) [reply tester/svgDemoCases/components/IssueFix.tsx]: 已格式化

**Review by Louis-C7 — APPROVED** [review]
