### PR TITLE
fix: SvgUse invalid when using with SvgMask

### LINKED ISSUE #280: Mask和Use一起使用时svg图像不显示
### 描述 / Description

mask组件导致svg图像不显示，demo如下：
```js
import React, {Component} from 'react';
import {
  View,
} from 'react-native';
import {SvgXml} from 'react-native-svg';

const billIcon = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="44px" height="44px" viewBox="0 0 44 44" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 57.1 (83088) - https://sketch.com -->
    <title>tabbar/resource/tab/fuwu@2x</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <rect id="path-1" x="0" y="0" width="44" height="44"></rect>
    </defs>
    <g id="tabbar/resource/tab/fuwu" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="购车1">
            <g id="Combined-Shape">
                <mask id="mask-2" fill="red">
                    <use xlink:href="#path-1"></use>
                </mask>
                <g id="Mask"></g>
                <path d="M33.8161936,4.05858201 C35.2420923,4.15633657 36.2446585,5.23457801 36.823892,7.29330633 C37.3197384,9.05565734 37.8870775,10.9745382 38.5259095,13.0499491 C39.3063258,12.9771117 41.2195294,12.983372 41.8378045,13.0701255 C42.2820448,13.1324593 42.66602,13.8950483 42.98973,15.3578925 C43.0463949,16.137888 42.8685735,16.5431751 42.4562659,16.5737539 C42.0716569,16.6022785 41.2579936,16.6609421 40.0152759,16.7497446 C40.8338182,18.5413061 41.4460857,19.7095209 41.8530164,20.2550339 C42.6015401,20.8972517 42.983868,21.9392245 43,23.3809524 L43,38.9258061 C42.7994439,39.94854 42.417116,40.5498159 41.8530164,40.7296336 C41.0068668,40.9993601 38.7201847,40.9749302 38.1052317,40.9993601 C37.4902788,41.0237901 36.6586996,40.3489751 36.219019,38.9258061 C36.1878692,38.8249798 36.0211841,36.787367 35.9898988,36.6846023 C35.8144919,36.108432 35.5917453,35.8208977 35.3216591,35.8219993 L9.22001377,35.8219993 C8.53135219,35.9042291 8.09917098,36.3926446 7.92347014,37.287246 C7.87981403,37.5095262 7.83699864,39.3536222 7.78701878,39.541862 C7.53527109,40.4900227 7.10175232,40.9993601 5.46344412,40.9993601 L2.36061548,40.9993601 C1.77908501,40.84713 1.43289544,40.1559453 1.32204678,38.9258061 C1.21119812,37.6956669 1.1038492,32.3271447 1,22.8202394 C1,21.9937791 1.34510756,21.1387106 2.03532267,20.2550339 C2.19523092,20.0409424 2.74597815,18.8710456 3.68756437,16.7453436 C2.59788523,16.6633715 1.87732723,16.6095172 1.52622349,16.5825449 C1.12719398,16.5518908 0.955099255,16.1456067 1.0099393,15.3636926 C1.32322442,13.89725 1.69483391,13.1327851 2.12476775,13.070298 C2.68805395,12.9884293 4.36193799,12.9780685 5.18724548,13.0392156 L7.02602592,7.29330633 C7.50256088,5.2149328 8.63918818,4.13669137 10.4359078,4.05858201 C12.2326275,3.98047266 20.0260561,3.98047266 33.8161936,4.05858201 Z M37.1661764,23.9872082 C37.1390951,23.9871165 37.1120576,23.9893945 37.0853733,23.994016 L28.4072765,25.4970015 C28.1853261,25.5354418 28.0229875,25.7276518 28.022225,25.9529052 L28.0182335,27.1320621 C28.0173655,27.3884785 28.2245285,27.5970488 28.480945,27.5979167 L28.4840895,27.5979167 L37.1571981,27.568534 C37.4123874,27.5676695 37.6190444,27.3610119 37.6199082,27.1058226 L37.6288879,24.4530628 C37.6297558,24.1966464 37.4225929,23.9880762 37.1661764,23.9872082 Z M7.55484255,23.9989394 C7.32691822,24.0000512 7.13815514,24.1652151 7.09990009,24.3819928 L7.09282698,24.4654842 L7.1054756,27.0586298 C7.10657971,27.2849872 7.26957218,27.473004 7.48462939,27.5128593 L7.56750189,27.5206454 L15.9637143,27.5614059 C16.1808415,27.56246 16.3656862,27.4138044 16.4164767,27.2096458 L16.4290406,27.1306686 L16.5127248,25.9753786 C16.527799,25.7672748 16.4027882,25.5787862 16.2139206,25.5075147 L16.12929,25.4844309 L7.63674478,24.0058149 C7.60970097,24.0011064 7.58229286,23.9988055 7.55484255,23.9989394 Z" stroke="#979797" stroke-width="2" mask="url(#mask-2)"></path>
            </g>
        </g>
    </g>
</svg>`

export default class SvgNativeMethods extends Component {
  render() {
    return (
      <View style={{margin:50}}>
        <SvgXml width="200" height="200" xml={billIcon} />
      </View>
    );
  }
}
```
安卓和web能显示出小车图像

### 复现步骤 / Steps to reproduce

none

### 库版本 / Library version

15.0.0-0.5.6

### React Native OpenHarmony version

0.72.28

### 构建类型 / Build type

None

### 设备 / Device

None

### 设备版本 / Device model

_No response_

### 已悉知 / Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by JCdahuzi**
# Summary

use 边界函数缺失，导致mask获取不到正确的组件边界，进而导致svg图像不能正常显示

## Test Plan

Test is available in svgDemoCases IssueFix section as "Issue#280".

closed #280

### CODE REVIEW

File: tester/harmony/svg/src/main/cpp/SvgUse.cpp [hunk 1]
```diff
@@ -35,6 +35,22 @@ void SvgUse::OnDraw(OH_Drawing_Canvas *canvas) {
     return;
 }
 
+drawing::Path SvgUse::AsPath() {
+    drawing::Path path;
+    auto svgContext = GetContext();
+    if (!svgContext) {
+        DLOG(INFO) << "[SvgUse::AsPath] : svgContext is a null ptr";
```
Comment (Louis-C7) [inline tester/harmony/svg/src/main/cpp/SvgUse.cpp]: 删掉

File: tester/harmony/svg/src/main/cpp/SvgUse.cpp [hunk 2]
```diff
@@ -35,6 +35,22 @@ void SvgUse::OnDraw(OH_Drawing_Canvas *canvas) {
...
+        return path;
+    }
+    auto refSvgNode = svgContext->GetSvgNodeById(href);
+    if (!refSvgNode) {
+        DLOG(INFO) << "[SvgUse::AsPath] : refSvgNode is a null ptr";
```
Comment (Louis-C7) [inline tester/harmony/svg/src/main/cpp/SvgUse.cpp]: 删掉

**Review by Louis-C7 — APPROVED** [review]
